// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Asset: typeof import('./src/components/Asset/index.vue')['default']
    Bind: typeof import('./src/components/Bind/index.vue')['default']
    CountDown: typeof import('./src/components/CountDown/index.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    Order: typeof import('./src/components/Order/index.vue')['default']
    Pay: typeof import('./src/components/Popup/pay.vue')['default']
    Popup: typeof import('./src/components/Popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step: typeof import('./src/components/Step/index.vue')['default']
    Team: typeof import('./src/components/Team/index.vue')['default']
  }
}

export {}
